USE customer_behavior;

SELECT * FROM customer
LIMIT 20;

-- Q1. What is the total revenue generated by male vs female customers?  
SELECT gender,
ROUND(AVG(purchase_amount),2) as total_revenue
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
ROUND(AVG(review_rating),2) AS highest_review
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average purchase amount between standard and express shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
ORDER BY avg_purchase_amount DESC;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers.
SELECT subscription_status,
COUNT(customer_id) AS total_cust,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend, total_revenue DESC;

-- Q6. Which 5 products has the highest percentage of purchases with discounts applied.
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100 / COUNT(*), 2) AS discount_rate 
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segments customers into 1 = New, between 2 and 10 as Returning and above it as Loyal , based on their total number 
-- 		of previous purchases and show the count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

SELECT customer_segment,
COUNT(*) AS 'Number of customer'
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH items_counts AS(
SELECT category, item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
) 

SELECT item_rank, category, item_purchased, total_orders 
FROM items_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of age group?
SELECT age_group,
SUM(purchase_amount) AS total_purchase
FROM customer
GROUP BY age_group
ORDER BY total_purchase DESC;

-- EXTRA QUESTIONS
-- Find the top 5 customers with the highest total purchase amount.
SELECT customer_id,
ROUND(SUM(purchase_amount)) AS total_purchase
FROM customer
GROUP BY customer_id
ORDER BY total_purchase DESC
LIMIT 5;


ALTER USER 'root'@'localhost'
IDENTIFIED WITH mysql_native_password BY 'Joker@52794';
FLUSH PRIVILEGES;










